// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://twuhjosfmrrrkcwvpivu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3dWhqb3NmbXJycmtjd3ZwaXZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NzcxNTAsImV4cCI6MjA3MzM1MzE1MH0.Pc-BMOBYg7G27qBgPdhMnmswb128WAvNmnmjCiIAtQU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});